### ISSUE TITLE
about dataset or checkpoint

### ISSUE THREAD

**Issue by HKCaesar** [manumathewthomas/CS523Project3#1]
Dear author,
It is a amzing work! Because of the internet,Ican not access the dataset url could you give a Google Driver ,OneDrive,dropbox url.
Thanks very much!

**Comment by manumathewthomas** [comment]
Sorry for the late reply:

here you go-

Dataset:
https://drive.google.com/file/d/1WI8X9Z218chjOlB-QB3bL8hIOWBMwLxE/view?usp=sharing

CheckPoint
https://drive.google.com/file/d/1bHTH6YnJU2UAl3DHici6jglE0KT1mWlk/view?usp=sharing

**Comment by yuxiaomu** [comment]
@manumathewthomas 您好，上面给出的链接都不能用了。打不开，请问还有其他地方可以下载数据集和训练好的模型吗

**Comment by Tian14267** [comment]
@yuxiaomu 请问你找到训练数据了吗？可否分享一份呢？
