### ISSUE TITLE
Abount model and checkpoint

### ISSUE THREAD

**Issue by XuSen123** [manumathewthomas/CS523Project3#2]
Dear author:
I can not access the dataset and checkpoint url, could you give me a Google Driver url or other? Thank you very much.

**Comment by manumathewthomas** [comment]
here you go-

**Dataset:**
https://drive.google.com/file/d/1WI8X9Z218chjOlB-QB3bL8hIOWBMwLxE/view?usp=sharing

**CheckPoint**
https://drive.google.com/file/d/1bHTH6YnJU2UAl3DHici6jglE0KT1mWlk/view?usp=sharing
